FROM golang:1.24 AS base
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /app/binary cmd/mcp/main.go

# Target "prod" for production mode.
FROM debian

COPY --from=base /app/binary /root/binary

EXPOSE 8080

WORKDIR /root
CMD ["/root/binary"]
